helmDefaults:
  # wait for k8s resources via --wait. (default false)
  wait: true
  # restores previous state in case of failed release (default false)
  atomic: true

helmfiles:
  - path: apps/nginx-ingress-controller/helmfile.yaml
  - path: apps/cert-manager/helmfile.yaml
  - path: apps/oauth2-proxy/helmfile.yaml
  - path: apps/k8s-dashboard-ingress/helmfile.yaml
  - path: apps/prometheus/helmfile.yaml
  - path: apps/argocd/helmfile.yaml