repositories:
- name: jetstack
  url: https://charts.jetstack.io

releases:
- name: certmanager
  namespace: cert-manager
  createNamespace: true
  chart: jetstack/cert-manager
  version: v1.8.0
  installed: true
  values:
    - installCRDs: true
  hooks:
  # Wait for the admission.certmanager.k8s.io apiservice to be ready before deploying ClusterIssuers
  # See https://github.com/helm/helm/issues/6361
  - events: ["postsync"]
    showlogs: true
    command: "sleep"
    args: ["120"]

- name: certmanager-issuer
  namespace: cert-manager
  needs:
    - cert-manager/certmanager
  chart: ./issuer-chart/
  version: v1.0.0
  installed: true
  disableValidationOnInstall: true
  values:
    - letsEncryptClusterIssuerEmail: {{ requiredEnv "LE_EMAIL" }}
