repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts

releases:
- name: prometheus
  namespace: prometheus
  createNamespace: true
  chart: prometheus-community/prometheus
  version: 15.8.1
  installed: true
  values:
    - values.yaml
