controller:
  # Prometheus
  metrics:
    enabled: true
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "10254"

  # Custom errors
  config:
    custom-http-errors: "404,500"

    # https://kubernetes.github.io/ingress-nginx/deploy/#digital-ocean
    # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#use-proxy-protocol
    use-proxy-protocol: true

  # https://kubernetes.github.io/ingress-nginx/#i-have-only-one-ingress-controller-in-my-cluster-what-should-i-do
  ingressClassResource:
    default: true

  # DigitalOcean specific timeout
  admissionWebhooks:
    timeoutSeconds: 29

  # https://kubernetes.github.io/ingress-nginx/deploy/#digital-ocean
  # https://github.com/kubernetes/ingress-nginx/blob/5737f166632a93011f6964b8b7ff7a977a5ecc43/charts/ingress-nginx/values.yaml#L178
  publishService:
    enabled: true
    pathOverride: "ingress-nginx/ingress-ingress-nginx-controller"

defaultBackend:
  enabled: true
  name: custom-default-backend
  image:
    repository: dvdblk/custom-default-backend
    tag: "latest"
    pullPolicy: Always
  port: 8080
  extraVolumeMounts:
    - name: tmp
      mountPath: /tmp
  extraVolumes:
    - name: tmp
      emptyDir: {}
