repositories:
- name: argo
  url: https://argoproj.github.io/argo-helm

releases:
- name: argocd
  namespace: argo-cd
  createNamespace: true
  chart: argo/argo-cd
  version: 4.5.3
  installed: true
  needs:
    - argo-cd/ghcr-registry-secret
  values:
    - server:
        ingress:
          enabled: true
          paths:
            - /
          hosts:
            - {{ requiredEnv "ARGOCD_HOST" }}
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/auth-url: https://{{ requiredEnv "OAUTH2_HOST" }}/oauth2/auth
            nginx.ingress.kubernetes.io/auth-signin: https://{{ requiredEnv "OAUTH2_HOST" }}/oauth2/start?rd=https%3A%2F%2F$host$request_uri
            kubernetes.io/tls-acme: "true"
            nginx.ingress.kubernetes.io/ssl-passthrough: "true"
            # If you encounter a redirect loop or are getting a 307 response code
            # then you need to force the nginx ingress to connect to the backend using HTTPS.
            #
            # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          tls:
            - secretName: prod-cert
              hosts:
                - {{ requiredEnv "ARGOCD_HOST" }}
        extraArgs:
          - --insecure
    - values.yaml
- name: ghcr-registry-secret
  namespace: argo-cd
  chart: ./ghcr-registry-secret-chart/
  version: 1.0.0
  installed: true
  values:
    - dockerconfigjson: {{ requiredEnv "GHCR_DOCKER_CONFIG_JSON" }}